POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "User3",
  "email": "user3@mail.com",
  "referrerId": "417a3f0a-88e1-4900-9995-03ebc82535c8"
}

###

GET http://localhost:3333/invites/f26a721f-ca72-4d11-a22b-5e5be68a9af7

###

GET http://localhost:3333/subscribers/f26a721f-ca72-4d11-a22b-5e5be68a9af7/ranking/clicks

###

GET http://localhost:3333/subscribers/417a3f0a-88e1-4900-9995-03ebc82535c8/ranking/count

###

GET http://localhost:3333/subscribers/f26a721f-ca72-4d11-a22b-5e5be68a9af7/ranking/position

###

GET http://localhost:3333/ranking

